const testEnvDefaults: Record<string, string> = {
  NODE_ENV: 'test',
  PORT: '3000',
  CORS_ORIGINS: 'http://localhost:3000,http://localhost:5173',
  BODY_JSON_LIMIT: '1mb',
  BODY_URLENCODED_LIMIT: '1mb',
  DATABASE_URL: 'postgresql://test:test@localhost:5432/mdc_test?schema=public',
  REDIS_URL: 'redis://localhost:6379',
  HEALTH_DATABASE_TIMEOUT_MS: '1000',
  HEALTH_REDIS_TIMEOUT_MS: '1000',
  S3_ENDPOINT: 'http://localhost:9000',
  S3_REGION: 'us-east-1',
  S3_ACCESS_KEY_ID: 'test-access-key',
  S3_SECRET_ACCESS_KEY: 'test-secret-key',
  S3_BUCKET: 'mdc-test',
  S3_FORCE_PATH_STYLE: 'true',
  HEALTH_S3_TIMEOUT_MS: '1000',
  ELASTICSEARCH_NODE: 'http://localhost:9200',
  HEALTH_ELASTICSEARCH_TIMEOUT_MS: '1000',
  SMTP_HOST: 'localhost',
  SMTP_PORT: '1025',
  SMTP_SECURE: 'false',
  SMTP_USER: 'test',
  SMTP_PASS: 'test',
  EMAIL_FROM: 'test@mdc.local',
  HEALTH_MAILER_TIMEOUT_MS: '1000',
  OTEL_SERVICE_NAME: 'mdc-be-test',
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318',
  APP_PROCESS_ROLE: 'all',
  JWT_ACCESS_SECRET: 'test-access-secret-min-32-chars-long',
  JWT_REFRESH_EXPIRES_IN: '7d',
  COOKIE_SECRET: 'test-cookie-secret-min-32-chars-long',
  COOKIE_SECURE: 'false',
  COOKIE_SAME_SITE: 'lax',
  BILLING_WEBHOOK_SECRET: 'test-billing-webhook-secret',
};

for (const [key, value] of Object.entries(testEnvDefaults)) {
  process.env[key] ??= value;
}
